name: tdd

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        racket-version: [ '7.3', '7.4' ]

    name: Racket ${{ matrix.racket-version }} sample

    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.3
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
      - run: bash run-tests.sh
